apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3
        failureThreshold: 5
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3
        failureThreshold: 7