apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3
        failureThreshold: 5
      readinessProbe:
        httpGet:
         path: /healthz
         port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 3
        failureThreshold: 7