apiVersion: v1
kind: Pod
metadata:
 name: demo-pod-2
spec:
 containers:
 - name: demo-container-1
   image: nginx
   resources:
     limits:
       memory: "200Mi"
       cpu: "200m"
     requests:
       memory: "100Mi"
       cpu: "100m"